# Seed data for some sample artists.
# All text content generated by ChatGPT 4.

require Ash.Query
import Ecto.Query

data = Ashify.Seeder.artists()
names = Enum.map(data, & &1.name)

# Delete the existing records for the seed data artists
# This may be run before the `destroy` action is defined on the resource,
# so may need to use Ecto directly.
if Ash.Resource.Info.action(Ashify.Music.Artist, :destroy) do
  Ashify.Music.Artist
  |> Ash.Query.filter(name in ^names)
  |> Ash.bulk_destroy!(:destroy, %{}, strategy: :stream, authorize?: false)
else
  from(a in Ashify.Music.Artist, where: a.name in ^names)
  |> Ashify.Repo.delete_all()
end

# And re-insert fresh copies of them
data
|> Ash.bulk_create!(Ashify.Music.Artist, :create, return_errors?: true, authorize?: false)
